[package]
name = "http-server-30"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.143"
axum = "0.8.4"
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread", "macros"] }
serde = { version = "1.0.219", features = ["derive"] }

